name: Smoke Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DISPLAY: ":99"
      ELECTRON_DISABLE_SANDBOX: "true"
      SMOKE_TEST: "true"

    steps:
      - name: Setup virtual display (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo "Virtual display started"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install Node dependencies
        run: npm ci

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          cd backend
          poetry config virtualenvs.in-project true
          poetry install

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Clean dist-electron directory
        run: |
          if [ -d "dist-electron" ]; then
            rm -rf dist-electron
            echo "dist-electron directory removed"
          else
            echo "dist-electron directory does not exist"
          fi

      - name: Run build
        run: npm run build:dev

      - name: Run smoke tests
        run: xvfb-run -a npm run test:smoke